5-feat/add-unit-tests

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -1,11 +1,19 @@
 echo '🏗️👷 Check lint and types before committing'
 
-bun lint-staged
+yarn lint-staged
 
 # Check tsconfig standards
-bun check-types ||
+yarn check-types ||
 (
     echo '🤡😂❌🤡 Failed Type check. 🤡😂❌🤡
+            Are you seriously trying to write that? Make the changes required above.'
+    false;
+)
+
+# Tests
+yarn test ||
+(
+    echo '🤡😂❌🤡 Failed Tests. 🤡😂❌🤡
             Are you seriously trying to write that? Make the changes required above.'
     false;
 )
